---

- name: Add mongodb yum repository
  template:
    src:   mongodb.yum.repo.j2
    dest:  /etc/yum.repos.d/mongodb-org-{{ mongodb_repo_version }}.repo
    owner: root
    group: root
    mode:  0644

- name: Install mongodb
  yum:
    name:  "mongodb-org-{{ mongodb_version|default('*') }}"
    state: present
  notify: Restart mongodb

- name: Ensure mongodb packages are up to date
  yum:
    name:  "{{ item }}-{{ mongodb_version|default('*') }}"
    state: present
  with_items: 
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  notify: Restart mongodb
