---

- name: Add mongodb yum repository
  template:
    src:   mongodb.yum.repo.j2
    dest:  /etc/yum.repos.d/mongodb-org-{{ mongodb_repo_version }}.repo
    owner: root
    group: root
    mode:  0644

# https://docs.mongodb.com/v3.0/tutorial/install-mongodb-on-red-hat/#install-the-mongodb-packages-and-associated-tools
- name: Install mongodb
  yum:
    name:  "{{ item }}-{{ mongodb_version|default('*') }}"
    state: present
  with_items: 
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  notify: Restart mongodb
