---

- name: Import mongodb-org public key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927

- name: Add mongodb-org apt repository to sources.list
  apt_repository: repo="{{ mongodb_apt_repo }}" state=present update_cache=yes

- name: Install mongodb
  apt: name=mongodb-org state=present
  notify: Restart mongodb

- name: Ensure mongodb db data directory exists
  file:
    path:  "{{ mongodb_data_dir }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode:  0755
    state: directory

- name: Update mongodb config file
  template: 
    src:   mongod.conf.j2
    dest:  /etc/mongod.conf
    owner: root
    group: root
    mode:  0644
  notify: Restart mongodb

- name: Update mongodb defaults settings config file
  template: 
    src:   etc.default.mongod.j2
    dest:  /etc/default/mongod
    owner: root
    group: root
    mode:  0644
  notify: Restart mongodb
  when: mongodb_apply_defaults_settings 

- name: Create disable-transparent-hugepages init script
  copy: 
    src:   disable-transparent-hugepages
    dest:  /etc/init.d/disable-transparent-hugepages
    owner: root
    group: root
    mode:  0755
  notify: Restart mongodb
  when: mongodb_disable_thp

- name: Enable disable-transparent-hugepages init script
  service: name=disable-transparent-hugepages enabled=yes
  when: mongodb_disable_thp

- name: Start mongodb
  service: name=mongod enabled=yes state=started

- include: replica_set.yml
  when: mongodb_create_replica_set
